version: '3.8'

services:
  admin:
    build:
      context: ./frontend/admin
    container_name: admin
    restart: always
    networks:
      - app-network

  web:
    build:
      context: ./frontend/web
    container_name: web
    restart: always
    networks:
      - app-network
  
  api:
    build:
      context: ./backend
    container_name: api
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - admin
      - web
      - api
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
