server {
    listen 80;

    # =========================
    # ADMIN (Refine)
    # =========================
    location /admin/ {
        proxy_pass http://admin/;
        proxy_set_header Host $host;
    }

    # =========================
    # WEB (user frontend)
    # =========================
    location / {
        proxy_pass http://web/;
        proxy_set_header Host $host;
    }

    # =========================
    # API
    # =========================
    location /api/ {
        proxy_pass http://api:3000/;
        proxy_set_header Host $host;
    }
}
